### ISSUE TITLE
[migration] Nvim 0.10 Support

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#1259]
### Feature description

The 0.10 stable version of `nvim` was released on 3 days ago. We could make some changes like #1245 to current 0.10 branch and merge it into `main`.

### Additional information

- **MANDATORY CHANGES**
  - [x] Update install scripts and issue templates to support v0.10. <==> https://github.com/ayamir/nvimdots/pull/1271 and https://github.com/ayamir/nvimdots/pull/1278
  - [ ] Consider **dropping** v0.7 (and v0.8) support. <==> `?`
  - [ ] Create two new branches: `0.9` (legacy) and `0.11` (nightly) <==> `?`
  - [x] Revisit all the Treesitter-related plugins to lift some of the performance limitations (as incremental parsing is finally supported) <==> https://github.com/ayamir/nvimdots/pull/1305
  - [x] Use the "signs" key of [vim.diagnostic.config()](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.config()) to configure [diagnostic-signs](https://neovim.io/doc/user/diagnostic.html#diagnostic-signs) <==> https://github.com/ayamir/nvimdots/pull/1280
  - [x] Use [vim.lsp.get_clients()](https://neovim.io/doc/user/lsp.html#vim.lsp.get_clients()) in place of [vim.lsp.get_active_clients()](https://neovim.io/doc/user/deprecated.html#vim.lsp.get_active_clients()) <==> https://github.com/ayamir/nvimdots/pull/1266
  - [x] Use [vim.uv](https://neovim.io/doc/user/lua.html#vim.uv) in place of [vim.loop](https://neovim.io/doc/user/deprecated.html#vim.loop) <==> https://github.com/ayamir/nvimdots/pull/1260
  - [x] Use [Iter:flatten()](https://neovim.io/doc/user/lua.html#Iter%3Aflatten()) in place of [vim.tbl_flatten()](https://neovim.io/doc/user/deprecated.html#vim.tbl_flatten()) <==> https://github.com/ayamir/nvimdots/pull/1260

- **NEW FEATURES**
  - [x] Support LSP Inlay Hints <==> https://github.com/ayamir/nvimdots/pull/1260
  - [x] Support new options <==> https://github.com/ayamir/nvimdots/pull/1279
  - [x] Consider replacing all accesses to Vim options from `vim.api.nvim_get_option_value` to `vim.[b]o` (as of v0.10, they finally function identically) <==> https://github.com/ayamir/nvimdots/pull/1269

### Linked issues / PRs
- [ ] #676
- [x] #851
- [x] #969
- [x] #1230
- [x] #1245
- [x] #1273
- [x] #1283

**Comment by CharlesChiuGit** [comment]
>  Support new options

after quite scan over https://neovim.io/doc/user/news-0.10.html and https://neovim.io/doc/user/deprecated.html#deprecated-0.10, i think it's fine w/ current option setup.

**Comment by Jint-lzxy** [comment]
> after quite scan over https://neovim.io/doc/user/news-0.10.html and https://neovim.io/doc/user/deprecated.html#deprecated-0.10, i think it's fine w/ current option setup.

Just took some time to read through the release notes. I think we could possibly implement those changes
```lua
- complete: ".,w,b,k" --> ".,w,b,k,kspell"
- completeopt: "menuone,noselect" --> "menuone,noselect,popup"
- smoothscroll: nil --> true
```
?
