### ISSUE TITLE
[migration] Nvim 0.9 Support

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#627]
### Feature description

Nvim v0.9.0 was [released yesterday](https://github.com/neovim/neovim/releases/tag/v0.9.0). This issue will be used to collect & discuss mandatory changes as well as new features during migration.

Git branch for migration: [0.9](https://github.com/ayamir/nvimdots/tree/0.9).

### Additional information

- **MANDATORY CHANGES**
  - [x] Update install scripts and issue templates to support v0.9. <==> https://github.com/ayamir/nvimdots/pull/630
  - [x] Consider **dropping** v0.7 support as it doesn't include version control. <==> https://github.com/ayamir/nvimdots/pull/630
  - [x] Update `hl_to_rgb` to use builtin `nvim_get_hl` instead. <==> https://github.com/ayamir/nvimdots/pull/632
  - [x] Remove legacy options (`:h news`) <==> https://github.com/ayamir/nvimdots/pull/631
  - [x] Update all `FUNC_API_DEPRECATED_SINCE(9)` API functions.
  - [x] **! Refactor Treesitter highlights** <==> https://github.com/ayamir/nvimdots/pull/676 **\* --> See 0.10**
  _\* Support for Treesitter highlights is currently a mess. The plan is to reimplement basic hl groups and link Treesitter's highlights to these basic hl groups to reduce maintenance pressure._

- **NEW FEATURES**
  - [x] Support LSP semantic tokens for catppuccin. <==> https://github.com/ayamir/nvimdots/pull/633
  - [x] Support new options <==> https://github.com/ayamir/nvimdots/pull/631

### Linked issues
- [x] #568 **- wontfix**
- [x] #612 
- [x] #617 
- [x] #624

**Comment by Jint-lzxy** [comment]
### Check before merging

Sometimes `nvim` crashes **during exit** (`:q`) _(at least on macOS)_ (SIGABRT), but it cannot be reliably reproduced. This would need to be tested on more platforms.

However, this issue only occurs after most plugins have been registered & loaded (e.g., a few seconds after opening a file for editing). Exiting from the dashboard will not lead to this issue, and `nvim --clean` doesn't lead to this issue either.

Backtrace points to `nvim` trying to close a handle that is either already closed or in a closing state. Blindly guessing, this should be related to a _specific_ plugin _(a pipeline created was released too early)_:
```c
assert(!uv__is_closing(handle)); // evaluates to assert(!true)
```

Current workaround:
```diff
diff --git a/src/nvim/event/stream.c b/src/nvim/event/stream.c
index 0a49186..9150873 100644
--- a/src/nvim/event/stream.c
+++ b/src/nvim/event/stream.c
@@ -139,7 +139,9 @@ void stream_close_handle(Stream *stream)
            (void *)stream,
            uv_stream_get_write_queue_size(stream->uvstream));
     }
-    uv_close((uv_handle_t *)stream->uvstream, close_cb);
+    if (!uv_is_closing((uv_handle_t *)stream->uvstream)) {
+      uv_close((uv_handle_t *)stream->uvstream, close_cb);
+    }
   } else {
     uv_close((uv_handle_t *)&stream->uv.idle, close_cb);
   }
```

Full stack backtrace (debug):
```console
Process:               nvim [719]
Path:                  /Users/USER/Desktop/*/nvim
Identifier:            nvim
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Exited process [718]
Responsible:           iTerm2 [502]
User ID:               501

Date/Time:             2023-04-09 03:47:41.7719 +0800
OS Version:            macOS 13.3 (22E252)
Report Version:        12
Bridge OS Version:     7.4 (20P4252)
Anonymous UUID:        D0515FBA-2DB1-0668-91ED-2B05D9C30992

Sleep/Wake UUID:       9A827DAC-35E4-42A9-8DF1-9F2B47823278

Time Awake Since Boot: 47000 seconds
Time Since Wake:       25442 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff808b321f2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff808b69ee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff808a90b45 abort + 123
3   libsystem_c.dylib             	    0x7ff808a8fe5e __assert_rtn + 314
4   nvim                          	       0x1038a3f74 uv_close + 84 (core.c:117)
5   nvim                          	       0x10350b2bd stream_close_handle + 157 (stream.c:142)
6   nvim                          	       0x10350bd21 write_cb + 209 (wstream.c:145)
7   nvim                          	       0x1038b7e8e uv__write_callbacks + 542 (stream.c:927)
8   nvim                          	       0x1038b7c10 uv__stream_destroy + 336 (stream.c:456)
9   nvim                          	       0x1038a7745 uv__finish_close + 293 (core.c:304)
10  nvim                          	       0x1038a48aa uv__run_closing_handles + 74 (core.c:334)
11  nvim                          	       0x1038a4644 uv_run + 404 (core.c:425)
12  nvim                          	       0x103506117 loop_close + 215 (loop.c:166)
13  nvim                          	       0x1033c6b09 event_teardown + 137 (main.c:170)
14  nvim                          	       0x1033cad83 os_exit + 67 (main.c:662)
15  nvim                          	       0x1033ca7d5 getout + 1493 (main.c:799)
16  nvim                          	       0x103529368 ex_exit + 360 (ex_docmd.c:4877)
17  nvim                          	       0x103521f7e execute_cmd0 + 894 (ex_docmd.c:1620)
18  nvim                          	       0x10351dbf9 do_one_cmd + 4921 (ex_docmd.c:2279)
19  nvim                          	       0x10351b697 do_cmdline + 2887 (ex_docmd.c:578)
20  nvim                          	       0x10361372d nv_colon + 349 (normal.c:3228)
21  nvim                          	       0x1036111a8 normal_execute + 2136 (normal.c:1196)
22  nvim                          	       0x10370d37a state_enter + 538 (state.c:99)
23  nvim                          	       0x10360d185 normal_enter + 165 (normal.c:497)
24  nvim                          	       0x1033c7d1d main + 4045 (main.c:641)
25  dyld                          	    0x7ff80881041f start + 1903

Thread 1:
0   libsystem_kernel.dylib        	    0x7ff808b2e0ee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff808b6a758 _pthread_cond_wait + 1242
2   nvim                          	       0x1038bbdbd uv_cond_wait + 29 (thread.c:911)
3   nvim                          	       0x10389c27c worker + 204 (threadpool.c:76)
4   libsystem_pthread.dylib       	    0x7ff808b6a1d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff808b65bd3 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff808b2e0ee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff808b6a758 _pthread_cond_wait + 1242
2   nvim                          	       0x1038bbdbd uv_cond_wait + 29 (thread.c:911)
3   nvim                          	       0x10389c27c worker + 204 (threadpool.c:76)
4   libsystem_pthread.dylib       	    0x7ff808b6a1d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff808b65bd3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff808b2e0ee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff808b6a758 _pthread_cond_wait + 1242
2   nvim                          	       0x1038bbdbd uv_cond_wait + 29 (thread.c:911)
3   nvim                          	       0x10389c27c worker + 204 (threadpool.c:76)
4   libsystem_pthread.dylib       	    0x7ff808b6a1d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff808b65bd3 thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	    0x7ff808b2e0ee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff808b6a758 _pthread_cond_wait + 1242
2   nvim                          	       0x1038bbdbd uv_cond_wait + 29 (thread.c:911)
3   nvim                          	       0x10389c27c worker + 204 (threadpool.c:76)
4   libsystem_pthread.dylib       	    0x7ff808b6a1d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff808b65bd3 thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	    0x7ff808b2b5b2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff808b3972d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff808b325e4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff808b2b89a mach_msg + 19
4   CoreFoundation                	    0x7ff808c461af __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff808c44c30 __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff808c44071 CFRunLoopRunSpecific + 560
7   CoreFoundation                	    0x7ff808cc7675 CFRunLoopRun + 40
8   nvim                          	       0x1038c4a0b uv__cf_loop_runner + 107 (fsevents.c:730)
9   libsystem_pthread.dylib       	    0x7ff808b6a1d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff808b65bd3 thread_start + 15

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff808b65bb0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7ff808b65bb0 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ff84c23d340  rcx: 0x00007ff7bcb39c48  rdx: 0x0000000000000000
  rdi: 0x0000000000000103  rsi: 0x0000000000000006  rbp: 0x00007ff7bcb39c70  rsp: 0x00007ff7bcb39c48
   r8: 0x0000000000000075   r9: 0xcccccccccccccccd  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000103  r13: 0x0000000103d67028  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff808b321f2  rfl: 0x0000000000000246  cr2: 0x0000000103d67000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133


Binary Images:
       0x1033c4000 -        0x103947fff nvim (*) <d547b91c-293a-3321-a609-7c36d55e050b> /Users/USER/Desktop/*/nvim
       0x103b7c000 -        0x103b87fff libintl.8.dylib (*) <146b350b-3118-3f81-aab0-b6792d3d810d> /usr/local/Cellar/gettext/0.21.1/lib/libintl.8.dylib
       0x1043cd000 -        0x1043d8fff lua.so (*) <f3f2e975-b3d2-3058-ad51-d238961a1b1d> /Users/USER/*/lua.so
       0x103d5b000 -        0x103d5efff libfzy-darwin-x86_64.so (*) <e0be7cbb-ce8f-3b19-883f-541e85282aaf> /Users/USER/*/libfzy-darwin-x86_64.so
    0x7ff808b2a000 -     0x7ff808b63ff7 libsystem_kernel.dylib (*) <08606a44-7008-3658-9f00-6c250b80e9c3> /usr/lib/system/libsystem_kernel.dylib
    0x7ff808b64000 -     0x7ff808b6ffff libsystem_pthread.dylib (*) <86dfa543-95fa-36b4-83c6-bf03d01b2aad> /usr/lib/system/libsystem_pthread.dylib
    0x7ff808a11000 -     0x7ff808a98ff7 libsystem_c.dylib (*) <0773ddbc-707e-3b56-ad3e-97aaa9b2c3ed> /usr/lib/system/libsystem_c.dylib
    0x7ff80880a000 -     0x7ff8088a25a7 dyld (*) <afa3518c-143e-3060-bbe8-624d4ca41063> /usr/lib/dyld
    0x7ff808bc9000 -     0x7ff809065fef com.apple.CoreFoundation (6.9) <315a3f65-0954-3635-96dc-2f65c691d074> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 28
    thread_create: 0
    thread_set_state: 1465

VM Region Summary:
ReadOnly portion of Libraries: Total=293.2M resident=0K(0%) swapped_out_or_unallocated=293.2M(100%)
Writable regions: Total=703.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=703.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           252.6M       53 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        8 
Stack                             49.1M        8 
VM_ALLOCATE                       17.4M      141 
__DATA                            3308K      141 
__DATA_CONST                      5778K      102 
__DATA_DIRTY                       343K       57 
__LINKEDIT                       172.3M        6 
__OBJC_RO                         66.2M        1 
__OBJC_RW                         2012K        2 
__TEXT                           120.9M      154 
dyld private memory                260K        2 
shared memory                       20K        3 
===========                     =======  ======= 
TOTAL                              1.1G      685 
TOTAL, minus reserved VM space   746.3M      685 
```

cc @ayamir @CharlesChiuGit

**Comment by ayamir** [comment]
Maybe we can checkout a 0.8 branch before merge changes for 0.9.

**Comment by Jint-lzxy** [comment]
> Maybe we can checkout a 0.8 branch before merge changes for 0.9.

[tree#0.8](https://github.com/ayamir/nvimdots/tree/0.8)

**Comment by ayamir** [comment]
Add [suda.vim](https://github.com/lambdalisue/suda.vim) is accpetable to close #617 but whether it is necessary.

**Comment by CharlesChiuGit** [comment]
> 

This is interesting, I never ran into this when I drove 0.9-dev on void, arch and ubuntu. I'll test the non-dev version again.
Is this error happens on macos?

**Comment by Jint-lzxy** [comment]
> Is this error happens on macos?

Yep.

> This is interesting, I never ran into this when I drove 0.9-dev on void, arch and ubuntu. I'll test the non-dev version again.

After attaching a debugger to `nvim` _(about to crash)_, looks like sometimes `uv_close` is called by an autocmd (a `uv_handle_t*`) registered by _a_ plugin (whose information can't be obtained as we're directly debugging an executable) that will trigger at `VimLeavePre`. Current observation indicates that only this callback would lead to a crash when calling external shell commands. The following:
```lua
vim.api.nvim_create_autocmd("VimLeavePre", {
	callback = function()
		vim.api.nvim_command([[silent! !echo 'aMessage']])
	end,
})
```
can reliably reproduce this crash on macOS. idk whether this behavior is the same on other platforms 😄

**Comment by CharlesChiuGit** [comment]
https://github.com/glepnir/lspsaga.nvim/commit/298009c345d1d519d7b6e60013817bbf549c19bc
```
    keys = {
      exec_action = 'o',
      exec_action = 'o',
      quit = 'q',
      quit = 'q',
      ~~ go_action = 'g', ~~
      expand_or_jump = '<CR>',
      expand_or_jump = '<CR>',
      quit_in_show = { 'q', '<ESC>' },
      quit_in_show = { 'q', '<ESC>' },
    },
```
`go_action` is now removed, @Jint-lzxy r u waiting for the new release?

**Comment by CharlesChiuGit** [comment]
> can reliably reproduce this crash on macOS. idk whether this behavior is the same on other platforms 😄

This doesn't seem to happen on Win11 with 0.9 (non-dev) version.

**Comment by ayamir** [comment]
> This doesn't seem to happen on Win11 with 0.9 (non-dev) version.

Don't appear on Gentoo too.

**Comment by Jint-lzxy** [comment]
> idk whether this behavior is the same on other platforms

Looks like this is an upstream issue: https://github.com/neovim/neovim/issues/21856.

> Also I think starting from now, we need to send PRs to 0.9 branch?

In fact, all previous PRs _were_ sent to the 0.9 branch 😄

> `go_action` is now removed

Oh well spotted! I somehow didn't notice this change

**Comment by CharlesChiuGit** [comment]
> It seems like our winbar is not currently enabled. Is this intentional?

@fecet 
ys, we tried it before.
It loads a bit later when the buffer is opened and causes the screen to shake a bit, especially on a slower machine. That's why we decide to move the lsp breadcrumbs to `lualine`.

**Comment by Jint-lzxy** [comment]
@fecet FYI: #398 and #402.

**Comment by fecet** [comment]
> @fecet FYI: #398 and #402.

I'm adding https://github.com/SmiteshP/nvim-navbuddy to my config, so I  can write a winbar PR based on nvim-navic if you find it useful. Also, the functionality mentioned in  #398  should have been fixed in neovim 0.9 version as @CharlesChiuGit  mentioned, so I think it might be appropriate to bring it back in this branch. 

The current solution doesn't work well for me because lsp symbols can be very long and lualine already takes up a lot of space on both sides.

**Comment by CharlesChiuGit** [comment]
maybe we cau just use lspsaga's winbar functionality, not need extra two plugins lol.

maybe we can see a pr first?

**Comment by fecet** [comment]
> maybe we cau just use lspsaga's winbar functionality, not need extra two plugins lol.
Maybe we should discuss if adding navbuddy? Since otherwise all we need to do is set option in lspsaga to true. I dont quite know how to sugget a new plugin in this project, though it's lightweight enough and should not hurt startuptime much.

**Comment by CharlesChiuGit** [comment]
> I dont quite know how to sugget a new plugin in this project, though it's lightweight enough and should not hurt startuptime much.

Normally I just test the plugin for a while and see if there's any weird thing, if I use it a lot then I'll post in #494.

> Maybe we should discuss if adding navbuddy?

I checked this plugin before when I was looking for sth like https://github.com/ziontee113/syntax-tree-surfer and https://github.com/mfussenegger/nvim-treehopper, but `navbuddy` need too much dependencies IMHO; therefore I drop it.

**Comment by fecet** [comment]
I have suggested the author of lspsaga to add functionality like navbuddy, he said he would implement that in a different but better way to replace current outline function. So I agree waitting is wise choice.

**Comment by CharlesChiuGit** [comment]
> I have suggested the author of lspsaga to add functionality like navbuddy, he said he would implement that in a different but better way to replace current outline function. So I agree waitting is a wise choice.

that would be nice!

**Comment by Jint-lzxy** [comment]
> The current solution doesn't work well for me because lsp symbols can be very long and lualine already takes up a lot of space on both sides.

💯💯 Agreed. That PR (#402) served as a workaround for a defect introduced in `nvim v0.8 + lspsaga` (which was fixed later in 0.9-dev). Many thanks for pointing this out 👍 It was proposed "ages ago" and I completely forgot this.

btw, we could also fill `lualine-c` with other plugins like git blame.

**Comment by Jint-lzxy** [comment]
Closing in favor of #1259.
