### ISSUE TITLE
Tidy and unified UI

### ISSUE THREAD

**Issue by volpan** [ayamir/nvimdots#698]
Straightly go to [this comment](https://github.com/ayamir/nvimdots/issues/698#issuecomment-1585716290).

### Feature description

The highlights for cmp, nvim-tree, wilder and indent-blankline now is untidy and always catch my focus when I should focus on my code.

### Additional information

I had already modified the highlights for them.

1. same appearance for cmp and wilder
2. clear appearance for bufferline and nvim-tree
3. colored indent-blankline
4. similar highlights for indent lines in nvim-tree, indent-blankline and outline of lspsaga

![image](https://user-images.githubusercontent.com/73375859/235570767-151f32b2-bef2-415d-a5f8-04b794ecb230.png)

![image](https://user-images.githubusercontent.com/73375859/235570884-5c7f5212-d526-4684-9242-70a953f41795.png)

So I'm here to get to know if I could give a PR.

**Comment by huge-pancake** [comment]
update: highlight for lspsaga's outline [lspsaga#1050](https://github.com/nvimdev/lspsaga.nvim/issues/1050#issue-1691710152)

![image](https://user-images.githubusercontent.com/73375859/235578477-68bbfb06-0916-48fa-8fa9-70b83b869234.png)

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy 's #676 PR should alleviate some of your issues. It's most from upstream, so it needs more time to finish it.

**Comment by huge-pancake** [comment]
You mean some of the problems are from `catppuccin/nvim` right? So I will wait for them :P

They other changes are not problems, they are just for customization (2, 3 and 4)

**Comment by CharlesChiuGit** [comment]
ys, of course u can send pr about 2, 3, 4 first!

**Comment by Jint-lzxy** [comment]
@huge-pancake Many thanks for your contribution 👍  But due to the complexity of #676 (most highlight groups and _actual hex codes_ for those _antonomasias_ \[e.g., `C.base -> #1E1E2E`\] will undergo significant changes), hence to avoid repetitive work, this PR will be merged after #676 is completed. I will also refer to your PR while reimplementing those hl groups.

Here is a sneak peak of Telescope's new UI _(based on your PR)_:

<img width="1792" alt="telescope-new-ui" src="https://user-images.githubusercontent.com/50296129/235711540-0e076386-8e94-4856-adc4-d6b37a6ecafe.png">

**Comment by huge-pancake** [comment]
Got it, hope #676/upstream update will come out soon.

Also there're some problems I haven't solve yet:

1. Window/Floating with border or not? If have, curved or not? It should be decided by users themselves, but changing all the options will be too hard and it's also hard when users want to change the UI style again. Maybe we can provide a option in `settings.lua` to control this. (also see [catppuccin/nvim#439](https://github.com/catppuccin/nvim/issues/439))
2. I'm using `WinSeparator` to hide border in outline (lspsaga) like nvim-tree, but this will influence all the borders between window and window. Maybe lspsaga should privide a highlight `OutlineBorder`.

![image](https://user-images.githubusercontent.com/73375859/235717039-c2ef97f8-2c3c-4b9a-b818-e43b31428a99.png)

3. Bufferline's inactive background (default is `crust`) should be lighter (NvChad) than the color of the tabs or darker (default, VSCode)?

Btw, I think in the field of UI, NvChad relly does very well.

**Comment by huge-pancake** [comment]
1. Borders: I can accept if borders can be united, too. I just don't like united UI design :P
2. Lspsaga: waiting for the author
3. Bufferline: agree

**Comment by nullchilly** [comment]
> Here is a sneak peak of Telescope's new UI _(based on your PR)_:
> 
> <img alt="telescope-new-ui" width="1792" src="https://user-images.githubusercontent.com/50296129/235711540-0e076386-8e94-4856-adc4-d6b37a6ecafe.png">

More than happy to merge this upstream under `telescope = { nvchad = true }`. However, I think the current Visual bg is too hard to see:

![image](https://user-images.githubusercontent.com/56817415/235949937-0c127d58-4558-4283-9561-ad34244194f8.png)

**Comment by huge-pancake** [comment]
I added something more, the PR is now at #718 (to follow branch naming spec).

**Comment by huge-pancake** [comment]
I also made a new lualine style like this

![image](https://user-images.githubusercontent.com/73375859/236655982-8341999d-2228-44e1-b44f-3371ad4b4532.png)

Not sure if I should add it into the PR.

**Comment by huge-pancake** [comment]
Highlights become broken when `transparent_background` is `true`

![image](https://user-images.githubusercontent.com/73375859/236656100-ecf1f58d-bd5f-4e87-8653-7260a145ee4b.png)

**Comment by CharlesChiuGit** [comment]
i think it's better to discuss the following polls or issues under the pr, so we don't need to check two places 😹

**Comment by CharlesChiuGit** [comment]
> I also made a new lualine style like this
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/73375859/236655982-8341999d-2228-44e1-b44f-3371ad4b4532.png)
> 
> 
> 
> Not sure if I should add it into the PR.

wow, that looks really nice! but why duplicate diagnostic sections?

**Comment by huge-pancake** [comment]
Highlights are now fixed at this [commit](https://github.com/ayamir/nvimdots/commit/c90f1aadd0bb4669b519d72e7a60bfcd1f10ee7d).

> duplicate diagnostic sections

hmm I didn't see any duplicate sections

`mode | filetype, filename | branch, diff /// /// disgnostic | workspace | location`

**Comment by CharlesChiuGit** [comment]
aha, sorry about that. i checked on my phone. i thought the git diffs are the diagnostics lol

**Comment by huge-pancake** [comment]
__Progress__

- [x] `cmp` and `wilder`, #772
- [ ] `bufferline` with `nvim-tree`, `outline (lspsaga)`.
- [ ] `indent-blankline`.
- [ ] `nvim-tree`, `indent-blankline` and `outline (lspsaga)`.
- [x] Float windows including `Telescope`, #772, #783
- [x] `ts-context`, #772
- [x] Highlight names for `alpha` change to the default, #772

**Comment by huge-pancake** [comment]
__Unsure styles for `nvim-tree`__

![image](https://github.com/ayamir/nvimdots/assets/73375859/580e8a3f-64ad-4498-b51a-d6aa73e9764a)

__Differences__

- Filenames highlighted.
- Git icons moved to the right.
- Git ignored files will still display, but with grey color.

**Comment by huge-pancake** [comment]
__Unsure styles for `indent-blankline`__

![image](https://github.com/ayamir/nvimdots/assets/73375859/5a5c9d0a-1a7d-4633-8567-42eb26f90920)

__Differences__

- Highlight current level start and with `surface0` bg.
- Highlight current level indent line with `surface1` fg.

**Comment by ayamir** [comment]
> Highlights are now fixed at this [commit](https://github.com/ayamir/nvimdots/commit/c90f1aadd0bb4669b519d72e7a60bfcd1f10ee7d).
> 
> > i think it's better to discuss the following polls or issues under the pr, so we don't need to check two places joy_cat
> 
> Sure.
> 
> > duplicate diagnostic sections
> 
> hmm I didn't see any duplicate sections
> 
> `mode | filetype, filename | branch, diff /// /// disgnostic | workspace | location`

IMO no need to add filename to `lualine` because it already appears in `bufferline`.

**Comment by ayamir** [comment]
> **Unsure styles for `nvim-tree`**
> 
> ![image](https://user-images.githubusercontent.com/73375859/244881156-580e8a3f-64ad-4498-b51a-d6aa73e9764a.png)
> 
> **Differences**
> 
> * Filenames highlighted.
> * Git icons moved to the right.
> * Git ignored files will still display, but with grey color.

I like it.

**Comment by huge-pancake** [comment]
__Unsure styles for `lualine`__

![image](https://github.com/ayamir/nvimdots/assets/73375859/2ffe7133-4b26-415b-8fe2-01d24351dd8a)

__Ref__

- [Jint-lzxy](https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537361782)
- [huge-pancake](https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537302480)

**Comment by huge-pancake** [comment]
> > **Unsure styles for `nvim-tree`**
> > ![image](https://user-images.githubusercontent.com/73375859/244881156-580e8a3f-64ad-4498-b51a-d6aa73e9764a.png)
> > **Differences**
> > 
> > * Filenames highlighted.
> > * Git icons moved to the right.
> > * Git ignored files will still display, but with grey color.
> 
> I like it.

Will make a pr next week.

**Comment by ayamir** [comment]
> **Unsure styles for `lualine`**
> 
> ![image](https://user-images.githubusercontent.com/73375859/244921419-2ffe7133-4b26-415b-8fe2-01d24351dd8a.png)
> 
> **Ref**
> 
> * [Jint-lzxy](https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537361782)
> * [huge-pancake](https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537302480)

Maybe it's better to swap the position of lsp servers and project dir. Because not all of files have lsp support, it will be more distinguishable.

**Comment by CharlesChiuGit** [comment]
> **Unsure styles for `nvim-tree`**
> 
> ![image](https://user-images.githubusercontent.com/73375859/244881156-580e8a3f-64ad-4498-b51a-d6aa73e9764a.png)
> 
> **Differences**
> 
>     * Filenames highlighted.
> 
>     * Git icons moved to the right.
> 
>     * Git ignored files will still display, but with grey color.

I like it too!

**Comment by CharlesChiuGit** [comment]
> **Unsure styles for `indent-blankline`**

LGTM!

**Comment by ayamir** [comment]
> be it's better to swap the position of lsp servers and project dir. Because not all of files have lsp support, it will be more distinguishable.

ok for me.

**Comment by huge-pancake** [comment]
> Maybe it's better to swap the position of lsp servers and project dir. Because not all of files have lsp support, it will be more distinguishable.

Maybe move both LSP servers and diagnostics to the center, move project directory and Python environment to the right like this?

(the Python environment can be displayed as well, though I don't use python so that it's not in the image)

![image](https://github.com/ayamir/nvimdots/assets/73375859/e1964951-bf9b-464f-97c8-2b882f5c15da)

Also, what about changing `cmdheight` from `2` to `1`? The current command line may takes too much place.

**Comment by ayamir** [comment]
> > Maybe it's better to swap the position of lsp servers and project dir. Because not all of files have lsp support, it will be more distinguishable.
> 
> Maybe move both LSP servers and diagnostics to the center, move project directory and Python environment to the right like this?
> 
> (the Python environment can be displayed as well, though I don't use python so that it's not in the image)
> 
> ![image](https://user-images.githubusercontent.com/73375859/246582539-e1964951-bf9b-464f-97c8-2b882f5c15da.png)
> 
> Also, what about changing `cmdheight` from `2` to `1`? The current command line may takes too much place.

LGTM.

**Comment by huge-pancake** [comment]
Do we need such a lot file information? Maybe we can check this out first.

![image](https://github.com/ayamir/nvimdots/assets/73375859/a0483a34-e8cc-46ab-a39c-49a51bc55e39)

**Comment by Jint-lzxy** [comment]
> Maybe move both LSP servers and diagnostics to the center, move project directory and Python environment to the right like this?

💯 Agreed! I mean we can classify those components as:
```console
-------------------------------------------------------------------------------
|Normal|main|<ft-icons>|         LSP~         |~/.config/nvim|<multi-sec>|50:1|
   a      b       c            (center)              x              y       z
-------------------------------------------------------------------------------
   |      |       |               |              |                  |       |
   |      |       |       LSP-related stuffs     |-- workspace      |       |
   |      |       |        (might be empty)           fileinfo -----|       |
   |      |       |------ edit status (RO, [+]...)                          |
   |      |----- git                                        editor info ----|
   |---- edit modes
```
The reason why LSP is placed in the center is b/c there'll be no missing components on the left- and right-hand sides under those unsupported file types.

> Also, what about changing `cmdheight` from `2` to `1`? The current command line may takes too much place.

Agreed

**Comment by Jint-lzxy** [comment]
> Do we need such a lot file information?

FWIW we should first classify those components and _then_ discuss what might be filled in for each section.

**Comment by huge-pancake** [comment]
![image](https://github.com/ayamir/nvimdots/assets/73375859/7a007295-764d-414a-adc2-1225d46c1db4)

A little bit hard to see.

**Comment by huge-pancake** [comment]
> > Do we need such a lot file information?
> 
> FWIW we should first classify those components and _then_ discuss what might be filled in for each section.

![image](https://github.com/ayamir/nvimdots/assets/73375859/0915e390-559b-4566-89e0-efdfe763b01b)

![image](https://github.com/ayamir/nvimdots/assets/73375859/31bd31da-f144-433c-99ff-b3663605bb54)

_* [Why I moved Git diff to section c](https://github.com/ayamir/nvimdots/issues/698#issuecomment-1595648055), or try some other solutions._

**Comment by ayamir** [comment]
> ![image](https://user-images.githubusercontent.com/73375859/246591987-7a007295-764d-414a-adc2-1225d46c1db4.png)
> 
> A little bit hard to see.

Agree

**Comment by volpan** [comment]
IMO the original lualine highlights are too shiny, so here's my new idea.

![image](https://github.com/ayamir/nvimdots/assets/73375859/db273986-b948-4f97-a215-2cc2e16e09f5)

**Comment by ayamir** [comment]
> IMO the original lualine highlights are too shiny, so here's my new idea.
> 
> ![image](https://user-images.githubusercontent.com/73375859/248206706-db273986-b948-4f97-a215-2cc2e16e09f5.png)

IMO no need for the filename due to duplicate with bufferline.

**Comment by volpan** [comment]
> > IMO the original lualine highlights are too shiny, so here's my new idea.
> > ![image](https://user-images.githubusercontent.com/73375859/248206706-db273986-b948-4f97-a215-2cc2e16e09f5.png)
> 
> IMO no need for the filename due to duplicate with bufferline.

It's only for myself as I set the `bufferline` option `always_show_bufferline` to `false`, it'll be filled with something other (as the spec @Jint-lzxy gave, like file state) if this really be merged.

**Comment by Jint-lzxy** [comment]
> IMO the original lualine highlights are too shiny, so here's my new idea.
> 
> ![image](https://user-images.githubusercontent.com/73375859/248206706-db273986-b948-4f97-a215-2cc2e16e09f5.png)

LGTM! @volpan It would be great if you could push a commit for this! I will make several minor adjustments, and if everything looks good, we could then propose a new major release 👍

btw, thanks very much for sticking with us! :D

**Comment by ayamir** [comment]
> we could then propose a new major release

Indeed, tons of changes have been pushed and a release is required 👍

**Comment by Jint-lzxy** [comment]
> Just wondering how can I sync this color scheme to every palette \<...\>

@volpan What u need is a function for ur custom theme and have that registered under `<event> ColorScheme` _(this works only for `catppuccin` but can be expanded to fit any colorscheme)_:
```lua
--- lualine.lua
return function()
	----------- other configs -----------

	local custom_theme = function()
		local cp = require("catppuccin.palettes").get_palette()
		return {
			normal = {
				a = { bg = cp.lavender, fg = cp.mantle, gui = "bold" },
				b = { bg = cp.surface1, fg = cp.lavender },
				c = { bg = cp.mantle, fg = cp.text },
			}
			-- More configs...
		}
	end
	vim.api.nvim_create_autocmd("ColorScheme", {
		group = vim.api.nvim_create_augroup("LualineColorScheme", { clear = true }),
		callback = function()
			require("lualine").setup({ options = { theme = custom_theme() } })
		end,
	})

	----------- other configs -----------

	require("lualine").setup({
		options = {
			theme = custom_theme(),
		},
		-- More configs...
	})
end

```

**Comment by volpan** [comment]
Got it, will a PR soon (the structure may be lengthy and jumbled, you probably need to modify it a lot :thinking: )
